#!/usr/bin/env node
/**
 * pipeline/load-data.js
 *
 * Reads Atlas_Graph/exports/signals.json and regenerates signal-atlas-data.js.
 * Run from the Signal Atlas repo root:
 *
 *   node pipeline/load-data.js
 *
 * Expects Atlas_Graph to be a sibling directory:
 *   ../Atlas_Graph/exports/signals.json
 */

import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const SIGNALS_PATH = resolve(__dirname, "../../Atlas_Graph/exports/signals.json");
const OUT_PATH = resolve(__dirname, "../public/signal-atlas-data.js");
const MAP_SOURCE =
  "https://catalog.data.gov/dataset/tiger-line-shapefile-2023-county-orleans-parish-la-topological-faces-polygons-with-all-geocodes";

const raw = JSON.parse(readFileSync(SIGNALS_PATH, "utf-8"));
const { exportedAt, atlasFeed, atlasMap } = raw;

// --- atlasBuild stats ---
const inputCount = atlasFeed.length;
const publicationCount = new Set(atlasFeed.map((i) => i.source).filter(Boolean)).size;
const familyCount = new Set(atlasFeed.map((i) => i.sourceFamily).filter(Boolean)).size;
const eventCount = atlasFeed.filter((i) => i.type === "event").length;
const cultureShare = Math.round((eventCount / inputCount) * 100);

const atlasBuild = {
  generatedAt: exportedAt,
  inputCount,
  publicationCount,
  familyCount,
  cultureShare,
  mapSource: MAP_SOURCE,
};

// --- emit signal-atlas-data.js ---
const out = `// Generated by pipeline/load-data.js — do not edit by hand.
// Source: Atlas_Graph/exports/signals.json (exported at ${exportedAt})
export const atlasBuild = ${JSON.stringify(atlasBuild, null, 2)};

export const atlasMap = ${JSON.stringify({ viewBox: atlasMap.viewBox, markers: atlasMap.markers, paths: atlasMap.paths, neighborhoods: atlasMap.neighborhoods || null, bounds: atlasMap.bounds || null }, null, 2)};

export const atlasFeed = ${JSON.stringify(atlasFeed, null, 2)};
`;

writeFileSync(OUT_PATH, out, "utf-8");

const events = atlasFeed.filter((i) => i.type === "event").length;
const sources = atlasFeed.filter((i) => i.type === "source").length;
console.log(`signal-atlas-data.js regenerated (${events} events, ${sources} sources)`);
