// check-static.mjs — the buildless-app gate.
//
//   node scripts/check-static.mjs apps/action
//
// Verifies a static app (action, pitch) obeys the token single-source rule and
// carries no stale Pages URLs. Checks, for the app dir given as argv[2]:
//
//   1. public/tokens.css exists and byte-matches the generated form of
//      packages/tokens/tokens.css.
//   2. public/index.html links tokens.css before styles.css.
//   3. public/styles.css redefines none of the locked custom properties
//      (--paper --ink --rule --signal --vermilion --grid-line) — those live in
//      tokens.css only.
//   4. No csandbatch.github.io URL appears outside a line marked
//      <!-- CANONICAL-CUTOVER -->.
//
// If the app's public/ is absent (its migration unit has not run yet), exits 0
// with a PENDING message so the gate is runnable before the apps land.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const appArg = process.argv[2];
if (!appArg) {
  console.error("usage: node scripts/check-static.mjs <app-dir>   e.g. apps/action");
  process.exit(2);
}

const appDir = path.resolve(root, appArg);
const publicDir = path.join(appDir, "public");
const rel = (p) => path.relative(root, p).split(path.sep).join("/");

if (!fs.existsSync(publicDir)) {
  console.log(`check-static ${appArg}: PENDING — ${rel(publicDir)} not present yet`);
  console.log("  (blocked on the app migration unit that creates public/)");
  process.exit(0);
}

const LOCKED_TOKENS = ["--paper", "--ink", "--rule", "--signal", "--vermilion", "--grid-line"];
const BANNER = `/* GENERATED by scripts/sync-tokens.mjs from packages/tokens/tokens.css. */
/* Do not edit this file. Edit the source and run: npm run tokens:sync */
`;

let failures = 0;
const fail = (msg) => {
  failures += 1;
  console.error(`fail: ${msg}`);
};

// 1. tokens.css present and matches source.
const source = path.join(root, "packages", "tokens", "tokens.css");
const appTokens = path.join(publicDir, "tokens.css");
if (!fs.existsSync(source)) {
  console.log("note: packages/tokens/tokens.css absent — skipping token match (PENDING U2.2)");
} else if (!fs.existsSync(appTokens)) {
  fail(`${rel(appTokens)} is missing — run: npm run tokens:sync`);
} else if (fs.readFileSync(appTokens, "utf8") !== BANNER + fs.readFileSync(source, "utf8")) {
  fail(`${rel(appTokens)} differs from packages/tokens/tokens.css — run: npm run tokens:sync`);
}

// 2. index.html links tokens.css before styles.css.
const indexHtml = path.join(publicDir, "index.html");
if (!fs.existsSync(indexHtml)) {
  fail(`${rel(indexHtml)} is missing`);
} else {
  const html = fs.readFileSync(indexHtml, "utf8");
  const tokensAt = html.indexOf("tokens.css");
  const stylesAt = html.indexOf("styles.css");
  if (tokensAt === -1) {
    fail(`${rel(indexHtml)} does not link tokens.css`);
  } else if (stylesAt !== -1 && tokensAt > stylesAt) {
    fail(`${rel(indexHtml)} links tokens.css after styles.css — tokens must come first`);
  }
}

// 3. styles.css redefines no locked token.
const stylesCss = path.join(publicDir, "styles.css");
if (fs.existsSync(stylesCss)) {
  const css = fs.readFileSync(stylesCss, "utf8");
  for (const token of LOCKED_TOKENS) {
    const re = new RegExp(`(^|[^\\w-])${token}\\s*:`, "m");
    if (re.test(css)) {
      fail(`${rel(stylesCss)} redefines locked token ${token} — it belongs in tokens.css only`);
    }
  }
}

// 4. No stale Pages URLs outside CANONICAL-CUTOVER-marked lines.
const walk = (dir) => {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walk(full);
    } else if (/\.(html|css|js|mjs)$/.test(entry.name)) {
      const lines = fs.readFileSync(full, "utf8").split(/\r?\n/);
      lines.forEach((line, i) => {
        if (line.includes("csandbatch.github.io") && !line.includes("CANONICAL-CUTOVER")) {
          fail(`${rel(full)}:${i + 1} stale Pages URL not marked <!-- CANONICAL-CUTOVER -->`);
        }
      });
    }
  }
};
walk(publicDir);

if (failures > 0) {
  console.error(`check-static ${appArg}: ${failures} problem(s).`);
  process.exit(1);
}
console.log(`check-static ${appArg}: ok`);
