// sync-tokens.mjs — single-source palette propagation.
//
// packages/tokens/tokens.css is the locked source of truth for the shared
// color system (ultraviolet :root + suited-chili [data-theme] blocks). The
// buildless static apps do not import from node_modules, so this script copies
// the source into each app's public/tokens.css with a GENERATED banner.
//
//   node scripts/sync-tokens.mjs           write each app copy from source
//   node scripts/sync-tokens.mjs --check   byte-compare copies against source
//
// Until packages/tokens/tokens.css exists (extracted in U2.2), this script is a
// no-op that exits 0 with a clear PENDING message, so the root gate is runnable
// from day one.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const source = path.join(root, "packages", "tokens", "tokens.css");
// Static apps that consume the palette (their public/ arrives in U2.3/U2.4).
const targets = ["action", "pitch"].map((app) =>
  path.join(root, "apps", app, "public", "tokens.css"),
);

const check = process.argv.includes("--check");

const BANNER = `/* GENERATED by scripts/sync-tokens.mjs from packages/tokens/tokens.css. */
/* Do not edit this file. Edit the source and run: npm run tokens:sync */
`;

function pending(reason) {
  console.log(`tokens:${check ? "check" : "sync"}: PENDING — ${reason}`);
  console.log("  (blocked on U2.2: packages/tokens/tokens.css extraction)");
  process.exit(0);
}

if (!fs.existsSync(source)) {
  pending("packages/tokens/tokens.css not present yet");
}

const sourceCss = fs.readFileSync(source, "utf8");
const expected = BANNER + sourceCss;

let failures = 0;

for (const target of targets) {
  const appDir = path.dirname(path.dirname(target)); // apps/<app>
  if (!fs.existsSync(appDir)) {
    console.log(`skip: ${path.relative(root, appDir)} not present yet`);
    continue;
  }
  if (check) {
    if (!fs.existsSync(target)) {
      failures += 1;
      console.error(`drift: ${path.relative(root, target)} is missing`);
      continue;
    }
    const actual = fs.readFileSync(target, "utf8");
    // Compare newline-insensitively: git checkout may rewrite line endings
    // depending on platform config, and that must never read as palette drift.
    const norm = (s) => s.replace(/\r\n/g, "\n");
    if (norm(actual) !== norm(expected)) {
      failures += 1;
      console.error(`drift: ${path.relative(root, target)} differs from source`);
    } else {
      console.log(`ok: ${path.relative(root, target)}`);
    }
  } else {
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, expected);
    console.log(`wrote: ${path.relative(root, target)}`);
  }
}

if (failures > 0) {
  console.error(`tokens:check failed — ${failures} file(s) out of sync. Run: npm run tokens:sync`);
  process.exit(1);
}
